# requiring the environment of NodeJS 8.9.x LTS (carbon)
image: node:8.9

# add 'node_modules' to cache for speeding up builds
cache:
  paths:
  - node_modules/ # Node modules and dependencies

stages:
- html
- ebook

before_script:
- apt-get -yqq update  && apt-get -o dir::cache::archives="apt-cache" -yqq install calibre
- yarn install --silent
- ./node_modules/.bin/gitbook fetch latest
- ./node_modules/.bin/gitbook install

# the 'pages' job will deploy and build your site to the 'public' path
html:
  stage: html
  script:
  - ./node_modules/.bin/gitbook build . build/html # build to public path
  artifacts:
    paths:
    - build/html
  only:
  - master # this job will affect only the 'master' branch

ebook:
  stage: ebook
  script:
  - ./node_modules/.bin/gitbook pdf ./ ./build/ebooks/ebook.pdf
  - ./node_modules/.bin/gitbook epub ./ ./build/ebooks/ebook.epub
  - ./node_modules/.bin/gitbook mobi ./ ./build/ebooks/ebook.mobi
  artifacts:
    paths:
    - build/ebooks
