# requiring the environment of NodeJS 8.9.x LTS (carbon)
image: phusion/passenger-nodejs
# add 'node_modules' to cache for speeding up builds
cache:
  paths:
  - node_modules/ # Node modules and dependencies
  - ~/.cache/pip/

stages:
- gitbook
- readthebooks

before_script:
- apt-get -yqq update  && apt-get -o dir::cache::archives="apt-cache" -yqq install calibre
- yarn install --silent
- ./node_modules/.bin/gitbook fetch latest
- ./node_modules/.bin/gitbook install
- apt -yqq install python3-pip
- pip3 install sphinx
- pip3 install recommonmark


# the 'pages' job will deploy and build your site to the 'public' path
gitbook:
  stage: gitbook
  script:
  - ./node_modules/.bin/gitbook build . build/gitbook
  - ./node_modules/.bin/gitbook pdf ./ ./build/gitbook/ebook.pdf
  - ./node_modules/.bin/gitbook epub ./ ./build/gitbook/ebook.epub
  - ./node_modules/.bin/gitbook mobi ./ ./build/gitbook/ebook.mobi
  artifacts:
    paths:
    - build/gitbook  # build to gitbook path
  only:
  - master # this job will affect only the 'master' branch

readthdocs:
  stage: readthedocs
  script:
  - sphinx-build -d _build/doctrees . ./build/html
  artifacts:
    paths:
    - build/readthedocs
  only:
  - master
