image: passcareer/docs
cache:
  paths:
  - node_modules/
before_script:
- npm install --silent
stage:
- gitbook
- readthedocs
gitbook:
  script:
  - ./node_modules/.bin/gitbook build ./ public/gitbook-html
  - ./node_modules/.bin/gitbook pdf ./ ./public/ebooks/ebook.pdf
  - ./node_modules/.bin/gitbook epub ./ ./public/ebooks/ebook.epub
  - ./node_modules/.bin/gitbook mobi ./ ./public/ebooks/ebook.mobi
  artifacts:
    paths:
    - public
readthedocs:
  script:
  - sphinx-versioning build . ./public/readthedocs-html
  - sphix-build -b epub . ./public/reathedocs-ebooks
  artifacts:
    paths:
    - public
