# requiring the environment of NodeJS 8.9.x LTS (carbon)
image: python:3.6-alpine

readthdocs:
  stage: readthedocs
  script:
  - pip install sphinx
  - pip install sphinx_rtd_theme
  - pip install recommonmark
  - sphinx-build -d _build/doctrees . _build/html
  - mv _build/html public
  artifacts:
    paths:
    - public
  only:
  - master
